name: "Build iOS app"

on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          set -xe

          python -m pip install --upgrade pip gdown
          gdown --id "https://drive.google.com/file/d/12eT0Hs0419VIZorWhYTvgDTpO7WCzdo2/view?usp=sharing" -O archive.zip
          unzip -o archive.zip -d .

          xcodebuild -list -project "RPG Maker MZ Framework for Xcode 12.xcodeproj"

          xcodebuild archive \
            -project "RPG Maker MZ Framework for Xcode 12.xcodeproj" \
            -scheme "RPG Maker MZ Framework for Xcode 12" \
            -archivePath "RPG Maker MZ Framework for Xcode 12.xcarchive" \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv "RPG Maker MZ Framework for Xcode 12.xcarchive/Products/Applications/"*.app Payload/
          zip -r TF27-iOS.ipa Payload
          mv TF27-iOS.ipa ${{ runner.temp }}/TF27-iOS.ipa

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: "TF27"
          path: ${{ runner.temp }}/TF27-iOS.ipa
          retention-days: 3
